name: Deploy to Amazon AWS

on:
  push:
    branches:
      - main  # ou a branch que você usa

  workflow_dispatch:  # permite executar na mão pelo botão

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: RestWithSpringBootErudioTaskDefinition
          service: RestWithSpringBootErudioService
          cluster: RestWithSpringBootErudioCluster
          wait-for-service-stability: true
